services:
  app:
    build: .
    image: streamlit_adm:1.0
    container_name: streamlit_adm
    command: streamlit run adm_panel.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - ./app:/code
    ports:
      - 8502:8501
    tty: true
    restart: always

networks:
  default:
    external: true
    name: npm_net
